#!/bin/sh  
echo Content-type: text/html
echo

  echo "<HEAD>"
  echo "<TITLE>httpd error log</TITLE>"
  echo "</HEAD>"
  echo "<BODY>"
  echo "<H1>httpd error log</H1>"
  echo "<PRE>"
  ll /opt/apache1.3.6/logs/error_log
  echo "**** last 100 lines ****"
  tail -100 /opt/apache1.3.6/logs/error_log 
  echo "***** end of log *****"
  echo "</PRE>"
  echo "</BODY>"
  echo `"$*"=""`

