#!/bin/bash
# This program creates a custom output listing the files in a directory.  

root="/data/dev.sis.www/htdocs/"
dir=`echo $QUERY_STRING | cut -c5-`

# prepare to output an html page
echo Content-Type: text/plain
echo ""

# list the files 
if [ -d "$root/$dir" ]; then
  cd $root/$dir
  find * -type f -maxdepth 0 -name '[!.]*'
fi
