#!/bin/sh 

eval `echo $QUERY_STRING| sed -e 's/'"'"'/%27/g' | sed 's/+/ /g' |\
        awk 'BEGIN{RS="&";FS="="}
     $1~/^[a-zA-Z][a-zA-Z0-9_]*$/ {
     printf "QS_%s=%c%s%c\n",$1,39,$2,39}'`

#search variables are:
# QS_name -name of sender
#   QS_email 
echo "Message from \"$QS_name\":" |cat >/tmp/cca$$
echo "Email: \"$QS_email\"" |cat >>/tmp/cca$$
echo "Organization \"$QS_organization\" "|cat >>/tmp/cca$$
echo "Phone \"$QS_phone\" " |cat >>/tmp/cca$$
echo "Fax \"$QS_fax\" "|cat >>/tmp/cca$$ 
echo "\\n"|cat >>/tmp/cca$$
echo $QS_comments|cat >>/tmp/cca$$
sed 's/%0D%0A/ /g' /tmp/cca$$  > /tmp/cca$$1
sed 's/%28/ /g' /tmp/cca$$1  > /tmp/cca$$2
sed 's/%2C/ /g' /tmp/cca$$2  > /tmp/cca$$3
sed 's/%27t/ /g' /tmp/cca$$3  > /tmp/cca$$4
  
mail  schutp@em.agr.ca </tmp/cca$$4 

# print thankyou message to sender

echo Content-type: text/html
echo
echo "<HEAD>"
echo "<TITLE>Thankyou for your comments</TITLE>"
echo "</HEAD>"
echo "<BODY>"
echo "<center><H1>Thank you for your comments</H1>"
echo "<img src="/usr/local/etc/httpd/htdocs/PUB/BRD/images/resource/linesilo.gif"><p>" 
echo "Your comments have been sent to Peter Schut.</center>"
echo "</BODY>"
echo "</HTML>"

#End run
rm /tmp/cca$$*
