#!/usr/bin/perl
#
#

require "ctime.pl";
$Date = &ctime(time);

if ($ENV{'REQUEST_METHOD'} eq "POST") {
	$form = <STDIN>;
} else { 
	$form = $ENV{'QUERY_STRING'};
}
@pairs = split(/&/,$form);

foreach $pair (@pairs)
{
	($name, $value) = split(/=/,$pair);

	$value =~ s/\+/ /g;
	
	$value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;	
	$value =~ s/~!/ ~!/g;
	$test{$name} .= $value;
	

}
if ($test{GIS} eq "ARC/INFO") {
print "Content-type: text/html\n\n";
print "<HTML>\n";
print "<HEAD>\n";
print "<TITLE>ARC/INFO: Mapping Component Table: Dominant value of $test{ITEM}</TITLE>\n";
print "</HEAD>\n";
print "<BODY>\n";
print "<H1>Mapping Component Table attributes using ARC/INFO:<BR>Dominant value of $test{ITEM}</H1>\n";
print "<I>To map the dominant $test{ITEM}, you need to</I><P>\n";
print "<PRE>\n";
print "/* summarize the contents of $test{ITEM} by polygon\n";
print "additem $test{SLC}.cmp $test{SLC}.cmp2 sl-$test{ITEM} 9 9 C\n";
print "\n";
print "&data ARC INFO\n";
print "ARC\n";
print "SELECT $test{SLC}.CMP2\n";
print "CONCATENATE SL-$test{ITEM} FROM SL,$test{ITEM}\n";
print "QUIT\n";
print "STOP\n";
print "&END\n";
print "\n";
print "frequency $test{SLC}.cmp2 $test{SLC}.$test{ITEM}\n";
print "sl-$test{ITEM}\n";
print "sl\n";
print "$test{ITEM}\n";
print "end\n";
print "percent\n";
print "end\n";
print "\n";
print "/* identify the highest percentage component\n";
print "statistics $test{SLC}.$test{ITEM} $test{SLC}.cmp_max sl\n";
print "maximum percent\n";
print "end\n";
print "\n";
print "&data ARC INFO\n";
print "ARC\n";
print "SELECT $test{SLC}.$test{ITEM}\n";
print "SORT ON SL\n";
print "SEL $test{SLC}.CMP_MAX\n";
print "SORT ON SL\n";
print "SELECT $test{SLC}.$test{ITEM}\n";
print "RELATE $test{SLC}.CMP_MAX 1 BY SL WITH SEQUENTIAL\n";
print "RESEL PERCENT = \$1MAX-PERCENT\n";
print "NSEL\n";
print "PURGE\n";
print "Y\n";
print "\n";
print "SEL $test{SLC}.CMP_MAX\n";
print "DELETE $test{SLC}.CMP_MAX\n";
print "Y\n";
print "SEL $test{SLC}.CMP2\n";
print "DELETE $test{SLC}.CMP2\n";
print "Y\n";
print "QUIT\n";
print "STOP\n";
print "&END\n";
print "</PRE>\n";
print "Now: relate the $test{SLC}.PAT to the new file $test{SLC}.$test{ITEM}, via SL, and map the $test{ITEM} field</I>\n";
print "<HR>These instructions were developed for ARC/INFO version 7.\n";
print "<HR><ADDRESS>\n";
print "<I>Source:  <A HREF=\"/cansis/citations/schut.html\">Peter Schut</A>\n";
print "<BR>Contact: <A HREF=\"/cansis/org/head.html\">Head, CanSIS</A>\n";
print "<BR>Updated:</I> 1996.06.04\n";
print "<BR>Generated:</I> $Date\n";
print "</ADDRESS>\n";
print "</BODY>\n";
print "</HTML>\n";
} else { 
print "Content-type: text/html\n\n";
print "<HTML>\n";
print "<HEAD>\n";
print "<TITLE>ARC/VIEW: Mapping Component Table: Dominant value of $test{ITEM}</TITLE>\n";
print "</HEAD>\n";
print "<BODY>\n";
print "<H1>Mapping Component Table attributes using ARCVIEW:<BR>Dominant value of $test{ITEM}</H1>\n";
print "To map the dominant $test{ITEM}, you need to<P>\n";
print "<OL><LI>summarize the contents of $test{ITEM} by polygon\n";
print "    <OL><LI><DT>Create a new view\n";
print "            <DD><I>Views ; New</I>\n";
print "        <LI><DT>Add the SLC coverage as a theme\n";
print "            <DD><I>View ; Add Theme ; /disk3/prod/cs95.001/pec001</I>\n";
print "        <LI><DT>Load the Component table\n";
print "            <DD><I>Tables ; Add ; /disk3/prod/cs95.001/pec001/info ; slc.cmp</I>\n";
print "        <LI><DT>Prepare a field to summarize $test{ITEM} by SLC polygon\n";
print "            <DD><I><OL><LI>Table ; Start Editing\n";
print "                       <LI>Edit ; Add Field ; sl-$test{ITEM} ; string ; 9 ; OK\n";
print "                       <LI>highlight the new sl-$test{ITEM} field in the slc.cmp table\n";
print "                       <LI>calculate the value to equal [Sl].asstring + [$test{ITEM}]\n";
print "                   </OL></I>\n";
print "        <LI><DT>summarize $test{ITEM} by SLC polygon in a new table\n";
print "            <DD><I><OL><LI>highlight the sl-$test{ITEM} field\n";
print "                       <LI>click the summarize button\n";
print "                       <LI>Sl ; First ; Add\n";
print "                       <LI>$test{ITEM} ; First ; Add\n";
print "                       <LI>Percent ; Sum ; Add ; OK (<B>$test{ITEM}bySL</B>)\n";
print "                   </OL></I>\n";
print "    </OL><P>\n";
print "    <LI>identify the highest percentage $test{ITEM} in each polygon\n";
print "    <OL><LI><DT>find the highest percentage $test{ITEM} in each polygon\n";
print "            <DD><I><OL><LI>highlight the first-sl field in $test{ITEM}bySL\n";
print "                       <LI>click the summarize button\n";
print "                       <LI>Sum_Percent ; Maximum ; Add ; OK  (<B>MAX%$test{ITEM}</B>)\n";
print "                   </OL></I>\n";
print "        <LI><DT>identify these records in $test{ITEM}bySL\n";
print "            <DD><I><OL><LI>Join MAX%$test{ITEM} to $test{ITEM}bySL via first-sl=first-sl\n";
print "                       <LI>Use Query builder to select those records where Sum-Percent = Max-Sum-Percent\n";
print "                   </OL></I>\n";
print "        <LI><DT>create a file (export, then import) with these records\n";
print "            <DD><I><OL><LI>File ; Export (<B>$test{ITEM}</B>)\n";
print "                       <LI>Tables ; Add\n";
print "                   </OL></I>\n";
print "    </OL><P>\n";
print "    <LI>map the $test{ITEM} values\n";
print "    <OL><LI><DT>Join $test{ITEM} to the PAT\n";
print "            <DD><I><OL><LI>Open the table of the active theme\n";
print "                       <LI>Join $test{ITEM} to Attributes of the polygon coverage via first-sl=sl\n";
print "                  </OL></I>\n";
print "        <LI><DT>map first-$test{ITEM}\n";
print "    </OL>\n";
print "</OL>\n";
print "<HR>These instructions were developed for ARCVIEW version 2.1\n";
print "<HR><ADDRESS>\n";
print "<I>Source:  <A HREF=\"/cansis/citations/schut.html\">Peter Schut</A>\n";
print "<BR>Contact: <A HREF=\"/cansis/org/head.html\">Head, CanSIS</A>\n";
print "<BR>Updated:</I> 1996.10.09\n";
print "<BR>Generated:</I> $Date\n";
print "</ADDRESS>\n";
print "</BODY>\n";
print "</HTML>\n";
}
